# Generated by Django 4.1.7 on 2023-09-12 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import exam.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('difficulty_level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('exam_id', models.CharField(max_length=6, unique=True)),
                ('exam_name', models.CharField(max_length=150)),
                ('duration', exam.services.CustomDuration()),
                ('instructions', models.TextField()),
                ('total_marks', models.PositiveIntegerField()),
                ('qualify_score', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True, help_text='Make Sure to Set Active-state while creating.')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('slug_exam', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('question_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=50)),
                ('response', models.JSONField(default=dict)),
                ('marks_scored', models.CharField(default='00', max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userresponse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_exams', models.ManyToManyField(blank=True, related_name='purchased_exams', to='exam.exam')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('questions_text', models.TextField(blank=True, null=True)),
                ('questions_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('optionA_text', models.TextField(blank=True, null=True)),
                ('optionA_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('optionB_text', models.TextField(blank=True, null=True)),
                ('optionB_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('optionC_text', models.TextField(blank=True, null=True)),
                ('optionC_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('optionD_text', models.TextField(blank=True, null=True)),
                ('optionD_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('answer', models.CharField(choices=[('A', 'optionA'), ('B', 'optionB'), ('C', 'optionC'), ('D', 'optionD')], max_length=1)),
                ('solution_text', models.TextField(blank=True, editable=False, null=True)),
                ('solution_image', models.ImageField(blank=True, editable=False, null=True, upload_to='images/')),
                ('difficulty_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.difficultylevel')),
                ('question_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.questiontype')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchase', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateTimeField()),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_dates', to='exam.exam')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_dates', to='exam.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_validated', models.BooleanField(blank=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='questions', to='exam.questions'),
        ),
    ]
