# Generated by Django 4.1.7 on 2023-09-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='option1_image',
            new_name='optionA_image',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option1_text',
            new_name='optionA_text',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option2_image',
            new_name='optionB_image',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option2_text',
            new_name='optionB_text',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option3_image',
            new_name='optionC_image',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option3_text',
            new_name='optionC_text',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option4_image',
            new_name='optionD_image',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option4_text',
            new_name='optionD_text',
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(choices=[('A', 'optionA'), ('B', 'optionB'), ('C', 'optionC'), ('D', 'optionD')], max_length=1),
        ),
    ]
