# Generated by Django 4.1.7 on 2023-09-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_rename_option1_image_questions_optiona_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='questions_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
