# Generated by Django 4.2.4 on 2023-09-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_rename_solution_questions_solution_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='questions', to='exam.questions'),
        ),
    ]
