# Generated by Django 4.2.4 on 2023-09-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_exam_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_id',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
